### ISSUE TITLE
PyPortal download fails

### ISSUE THREAD

**Issue by ATMakersBill** [adafruit/Adafruit_CircuitPython_ESP32SPI#54]
Hi folks, I have a project that needs the PyPortal to download multiple .wav, .bmp, and .json files from a server.  It then caches them on the SD card.

I am getting these errors when downloading multiple files:
`Fetching stream from http://api.atmakers.org/sounds/Joey/next.wav
Traceback (most recent call last):
  File "code.py", line 92, in <module>
  File "code.py", line 54, in loadBoard
  File "code.py", line 42, in cacheFile
  File "adafruit_pyportal.py", line 600, in wget
  File "adafruit_esp32spi/adafruit_esp32spi_requests.py", line 241, in get
  File "adafruit_esp32spi/adafruit_esp32spi_requests.py", line 226, in request
  File "adafruit_esp32spi/adafruit_esp32spi_socket.py", line 153, in close
  File "adafruit_esp32spi/adafruit_esp32spi.py", line 618, in socket_close
  File "adafruit_esp32spi/adafruit_esp32spi.py", line 308, in _send_command_get_response
  File "adafruit_esp32spi/adafruit_esp32spi.py", line 297, in _wait_response_cmd
  File "adafruit_esp32spi/adafruit_esp32spi.py", line 281, in _wait_response_cmd
  File "adafruit_esp32spi/adafruit_esp32spi.py", line 257, in _wait_spi_char
RuntimeError: Error response to command`

If I rerun, it succeeds in that file just to fail a few files further down the list.

I am running CP 4.0.1 and the latest published 4.x libraries.  Is there an ESP update I'm missing?  If so, how do I tell?

(On a separate note, I am still getting hard crashes into safe mode after a minute or so... I'll file that in a separate issue if an update doesn't fix it).

**Comment by kattni** [comment]
@ATMakersBill Are you still running into this issue with CircuitPython 5.x and the latest lib bundle?
