### ISSUE TITLE
WSGI Server example fails trying to import `parse_headers`

### ISSUE THREAD

**Issue by siddacious** [adafruit/Adafruit_CircuitPython_ESP32SPI#62]
```
>>> import server_test
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "server_test.py", line 9, in <module>
  File "adafruit_esp32spi/adafruit_esp32spi_wsgiserver.py", line 53, in <module>
ImportError: cannot import name parse_headers
```
there is no `parse_headers` in `adafruit_requests`, it was inlined into the body of the `request` method

**Comment by siddacious** [comment]
Fixed, thanks to @brentru . It does
